version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    - requirements: docs/requirements.txt
    # Install our python package before building the docs
    - method: pip
      path: .
      extra_requirements:
        - docs  # If your flit package specifies extra dependencies for docs
  system_packages: true  # Enable system packages if needed for binary dependencies

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub