[build-system]
requires = [
    "flit_core >=2,<4",
    "numpy"  # Ensure numpy is listed here
]
build-backend = "flit_core.buildapi"

[project]
name = "py_champ"
authors = [{name = "Chung-Yi Lin", email = "philip928lin@gmail.com"}]
dynamic = ["version", "description"]
