[build-system]
<<<<<<< Updated upstream
requires = [
    "flit_core >=2,<4",
    "numpy",
    "pandas",
    "mesa==2.1.1",
    "scipy",
    "gurobipy",
    "sphinx-autoapi"
]
build-backend = "flit_core.buildapi"

[project]
name = "py_champ"
authors = [{name = "Chung-Yi Lin", email = "philip928lin@gmail.com"}]
dynamic = ["version", "description"]
=======
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "py_champ"
version = "1.0.0"
authors = [
    {name = "Chung-Yi Lin", email = "philip928lin@gmail.com"}
]
license = {text = "GNU General Public License v3 (GPLv3)"}
dynamic = ["description", "readme"]
dependencies = [
  "numpy",
  "pandas",
  "gurobipy",
  "scipy",
  "joblib",
  "mesa==2.1.1"
]
>>>>>>> Stashed changes
